### PR TITLE
Update react to 15.1.0

### PR DESCRIPTION
**Pull request by t3chnoboy**
Hi!
Thanks for bringing `devcards` to js! Hopefully it will catch up with cljs devcards 😄 
I had problems integrating it into my project because of the outdated react version.
After upgrading react to the latest stable version everything seems to work fine. Tests are green. The example project works.

### CODE REVIEW

**Comment by glenjamin** [comment]
Ah, the CI failure on the PR looks like it's because my "clever" autopublish script wasn't smart enough to not try and run for a PR!

I've just noticed I have something quite similar stashed on my local machine from 3 weeks ago!

Whoops :shipit:

**Comment by t3chnoboy** [comment]
thanks @glenjamin! 😊

**Comment by glenjamin** [comment]
Any other feedback you have is much appreciated!

**Comment by glenjamin** [comment]
Released as `v0.6.0`

**Pull request merged**
